### ISSUE TITLE
ServerlessError: In the command you just typed, the "function" is valid but "prune" is not.

### ISSUE THREAD

**Issue by rentrop** [Nopik/serverless-lambda-prune-plugin#12]
After installing the function in my project root via `npm install serverless-lambda-prune-plugin` i do run

`sls function prune` and get the following error:

> ServerlessError: In the command you just typed, the "function" is valid but "prune" is not.

What am i doing wrong?

Here is the full error:

```
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

ServerlessError: In the command you just typed, the "function" is valid but "prune" is not.  Enter "serverless help" to see the actions for this context.
  at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
  at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:363:31)
  at /usr/local/lib/node_modules/serverless/bin/serverless:19:16
  at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
  at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:18:4)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:134:18)
  at node.js:962:3
```

I am running serverless v 0.5.5

**Comment by segf4u1t** [comment]
+1

**Comment by dcroswell** [comment]
I've just gotten the same error.

**Comment by tszajna0** [comment]
And your s-project.json contains the "serverless-lambda-prune-plugin" in plugins, right?

**Comment by rentrop** [comment]
Yes it does. My Plugin array reads as follows:

```
"plugins": [
    "serverless-optimizer-plugin",
    "serverless-client-s3",
    "serverless-offline",
    "serverless-cors-plugin"
  ]
```

Maybe there is some complication with one of the other plugins, of v 0.5.5

**Comment by tszajna0** [comment]
@rentrop then it's interesting; for me works fine (with a different set of plugins).
I'll check it.

**Comment by benaghaeipour** [comment]
@rentrop that list doesn't contain "serverless-lambda-prune-plugin", double check ..?

**Comment by rentrop** [comment]
@benaghaeipour now it works. Thanks.

Just added wrote a pull-request as it is not mentioned in the installation guide - and i forgot it...
https://github.com/Nopik/serverless-lambda-prune-plugin/pull/13
