### ISSUE TITLE
Run during `function deploy`

### ISSUE THREAD

**Issue by arabold** [Nopik/serverless-lambda-prune-plugin#4]
In my opinion this plugin should run right after an `sls function deploy` to prune the just deployed Lambda. I'm not a big fan that it touches Lambdas that aren't part of the current project/component. In fact, I would suggest to even remove that to avoid accidental deletions.

With the new plugin framework this should be easy to achieve. Let me know if I can help.

**Comment by Nopik** [comment]
1) I dont agree that it should run automatically after function deploy, I would strongly prefer to have my CI running it as a separate command

2) Indeed, I'm planning the switch (enabled by default) to work only on a project lambdas.
